"""vLLM integration for natural-language recommendation outputs."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from typing import Any
from urllib import error, request

from app.services.recommendation_engine.aggregator import AggregatedForecastFeatures
from app.services.recommendation_engine.rules import RuleBasedRecommendation


@dataclass(slots=True)
class LLMRecommendationText:
    """Natural-language artifacts generated by the LLM."""

    summary: str
    explanation: str
    supplier_document_draft: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(slots=True)
class LLMReportText:
    summary: str

    def to_dict(self) -> dict:
        return asdict(self)


class VLLMWriter:
    """Client for OpenAI-compatible vLLM `/v1/chat/completions` API."""

    def __init__(
        self,
        *,
        base_url: str,
        model: str = "Qwen/Qwen2.5-7B-Instruct",
        api_key: str | None = None,
        timeout_sec: int = 30,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.api_key = api_key
        self.timeout_sec = timeout_sec

    def _build_prompt(
        self,
        *,
        store_id: int | str,
        features: AggregatedForecastFeatures,
        recommendation: RuleBasedRecommendation,
    ) -> str:
        return (
            "You are an inventory planning assistant. "
            "Use only provided forecast metrics and rule outputs.\n\n"
            f"Store ID: {store_id}\n"
            f"Metrics: {json.dumps(features.to_dict(), ensure_ascii=False)}\n"
            f"Rule recommendation: {json.dumps(recommendation.to_dict(), ensure_ascii=False)}\n\n"
            "Return STRICT JSON with keys:\n"
            "- summary: short recommendation summary (1-2 sentences)\n"
            "- explanation: concise rationale based on metrics and risk\n"
            "- supplier_document_draft: draft message to supplier with requested quantity and urgency\n"
            "No markdown. No additional keys."
        )

    def generate_text(
        self,
        *,
        store_id: int | str,
        features: AggregatedForecastFeatures,
        recommendation: RuleBasedRecommendation,
    ) -> LLMRecommendationText:
        payload = {
            "model": self.model,
            "temperature": 0.2,
            "messages": [
                {
                    "role": "system",
                    "content": "You produce concise business inventory recommendations.",
                },
                {
                    "role": "user",
                    "content": self._build_prompt(
                        store_id=store_id,
                        features=features,
                        recommendation=recommendation,
                    ),
                },
            ],
        }

        body = json.dumps(payload).encode("utf-8")
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        req = request.Request(
            url=f"{self.base_url}/v1/chat/completions",
            data=body,
            headers=headers,
            method="POST",
        )

        try:
            with request.urlopen(req, timeout=self.timeout_sec) as response:
                response_payload = json.loads(response.read().decode("utf-8"))
        except error.HTTPError as exc:
            details = exc.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"vLLM HTTP error {exc.code}: {details}") from exc
        except error.URLError as exc:
            raise RuntimeError(f"vLLM connection error: {exc.reason}") from exc

        try:
            content = response_payload["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise RuntimeError("Unexpected vLLM response format.") from exc

        parsed = _parse_json_content(content)
        return LLMRecommendationText(
            summary=str(parsed.get("summary", "")).strip(),
            explanation=str(parsed.get("explanation", "")).strip(),
            supplier_document_draft=str(parsed.get("supplier_document_draft", "")).strip(),
        )

    def generate_management_summary(self, *, payload: dict[str, Any]) -> LLMReportText:
        request_payload = {
            "model": self.model,
            "temperature": 0.2,
            "messages": [
                {
                    "role": "system",
                    "content": "You write concise management summaries for retail demand planning.",
                },
                {
                    "role": "user",
                    "content": (
                        "Generate a structured management summary with 3 blocks:\n"
                        "1) Executive summary\n"
                        "2) Main insights\n"
                        "3) Store-level actions\n\n"
                        f"Data: {json.dumps(payload, ensure_ascii=False)}\n\n"
                        "Return strict JSON with key `summary` only. "
                        "The value must be plain text with headings and bullet points."
                    ),
                },
            ],
        }
        body = json.dumps(request_payload).encode("utf-8")
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        req = request.Request(
            url=f"{self.base_url}/v1/chat/completions",
            data=body,
            headers=headers,
            method="POST",
        )
        try:
            with request.urlopen(req, timeout=self.timeout_sec) as response:
                response_payload = json.loads(response.read().decode("utf-8"))
        except error.HTTPError as exc:
            details = exc.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"vLLM HTTP error {exc.code}: {details}") from exc
        except error.URLError as exc:
            raise RuntimeError(f"vLLM connection error: {exc.reason}") from exc

        content = response_payload["choices"][0]["message"]["content"]
        parsed = _parse_json_content(content)
        return LLMReportText(summary=str(parsed.get("summary", "")).strip())


def _parse_json_content(content: str) -> dict[str, Any]:
    raw = content.strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        start = raw.find("{")
        end = raw.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise RuntimeError("LLM response is not valid JSON.")
        try:
            return json.loads(raw[start : end + 1])
        except json.JSONDecodeError as exc:
            raise RuntimeError("LLM response contains malformed JSON.") from exc
