"""initial_schema

Revision ID: c873a1a8d077
Revises: 
Create Date: 2026-06-28 15:04:36.244989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c873a1a8d077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('model_type', sa.Enum('BASELINE', 'GRADIENT_BOOSTING', 'RANDOM_FOREST', 'CUSTOM', name='modeltype'), nullable=False),
    sa.Column('features_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('store_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('assortment', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('competition_distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_external_id'), 'store', ['external_id'], unique=True)
    op.create_table('tariffplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('price_month', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffplan_name'), 'tariffplan', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ANALYST', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'VALIDATING', 'READY', 'FAILED', name='datasetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_uploaded_by'), 'dataset', ['uploaded_by'], unique=False)
    op.create_table('salesrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('customers', sa.Integer(), nullable=False),
    sa.Column('promo', sa.Boolean(), nullable=False),
    sa.Column('promo2', sa.Boolean(), nullable=False),
    sa.Column('school_holiday', sa.Boolean(), nullable=False),
    sa.Column('state_holiday', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salesrecord_date'), 'salesrecord', ['date'], unique=False)
    op.create_index(op.f('ix_salesrecord_store_id'), 'salesrecord', ['store_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tariff_plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIAL', 'PAUSED', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_plan_id'], ['tariffplan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_tariff_plan_id'), 'subscription', ['tariff_plan_id'], unique=False)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.create_table('subscriptionfeature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_plan_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_plan_id'], ['tariffplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptionfeature_tariff_plan_id'), 'subscriptionfeature', ['tariff_plan_id'], unique=False)
    op.create_table('usagelimit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_plan_id', sa.Integer(), nullable=False),
    sa.Column('max_forecast_runs_per_month', sa.Integer(), nullable=False),
    sa.Column('max_stores', sa.Integer(), nullable=False),
    sa.Column('max_reports', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tariff_plan_id'], ['tariffplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usagelimit_tariff_plan_id'), 'usagelimit', ['tariff_plan_id'], unique=False)
    op.create_table('forecastrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='forecastrunstatus'), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['modelversion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecastrun_created_by'), 'forecastrun', ['created_by'], unique=False)
    op.create_index(op.f('ix_forecastrun_dataset_id'), 'forecastrun', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_forecastrun_model_version_id'), 'forecastrun', ['model_version_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_subscription_id'), 'payment', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payment_transaction_id'), 'payment', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('predicted_sales', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecastrun.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_date'), 'forecast', ['date'], unique=False)
    op.create_index(op.f('ix_forecast_forecast_run_id'), 'forecast', ['forecast_run_id'], unique=False)
    op.create_index(op.f('ix_forecast_store_id'), 'forecast', ['store_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('expected_demand', sa.Float(), nullable=False),
    sa.Column('recommended_order', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecastrun.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_forecast_run_id'), 'recommendation', ['forecast_run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_store_id'), 'recommendation', ['store_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecastrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_created_by'), 'report', ['created_by'], unique=False)
    op.create_index(op.f('ix_report_forecast_run_id'), 'report', ['forecast_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_forecast_run_id'), table_name='report')
    op.drop_index(op.f('ix_report_created_by'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_recommendation_store_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_forecast_run_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_forecast_store_id'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_forecast_run_id'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_date'), table_name='forecast')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_transaction_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_subscription_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_forecastrun_model_version_id'), table_name='forecastrun')
    op.drop_index(op.f('ix_forecastrun_dataset_id'), table_name='forecastrun')
    op.drop_index(op.f('ix_forecastrun_created_by'), table_name='forecastrun')
    op.drop_table('forecastrun')
    op.drop_index(op.f('ix_usagelimit_tariff_plan_id'), table_name='usagelimit')
    op.drop_table('usagelimit')
    op.drop_index(op.f('ix_subscriptionfeature_tariff_plan_id'), table_name='subscriptionfeature')
    op.drop_table('subscriptionfeature')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_tariff_plan_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_salesrecord_store_id'), table_name='salesrecord')
    op.drop_index(op.f('ix_salesrecord_date'), table_name='salesrecord')
    op.drop_table('salesrecord')
    op.drop_index(op.f('ix_dataset_uploaded_by'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tariffplan_name'), table_name='tariffplan')
    op.drop_table('tariffplan')
    op.drop_index(op.f('ix_store_external_id'), table_name='store')
    op.drop_table('store')
    op.drop_table('modelversion')
    # ### end Alembic commands ###
